<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-A01793546-Ariel-Corral-Leon/blob/main/assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
print('assignment01 for GitJobish03 and edited in git, and 18')

assignment01 for GitJobish03 and edited in git, and 18


In [64]:
print("Hola desde Monterrey \nMi nombre es Ariel Corral")

Hola desde Monterrey 
Mi nombre es Ariel Corral


In [65]:
Var1 = 1

In [66]:
Var2=1.03
Var3= True
Var4= "Cadena de texto"

In [67]:
print(type(Var1))

print(type(Var2))

print(type(Var3))

print(type(Var4))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


In [68]:
Nombre=print("Bienvenido a estas primeras pruebas y aprendizaje ", input("Escribe tu nombre para desplegarlo : ") )

Escribe tu nombre para desplegarlo : Ariel Corral
Bienvenido a estas primeras pruebas y aprendizaje  Ariel Corral


In [69]:

S={'A','B','C'}

U={'A','Z','C'}

U.union(S)

{'A', 'B', 'C', 'Z'}

In [70]:
Q = {'a':0,'b':1,'c':2}

In [71]:
print(Q)

{'a': 0, 'b': 1, 'c': 2}


In [72]:
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}
Dict["D"]

Dict["E"]

5

In [73]:
A=[3,4,5]

for a in A:

  print(a)

3
4
5


In [74]:
x=3

y=1

while(y!=x):

  print(y)

  y=y+1

1
2


In [75]:
a=1

def add(b):

  return a+b

c=add(10)
print(c)

11


In [76]:
def f(*x):

  return sum(x)
print(x)


3


# Modulo 4
#### Avanzando a la lectura de documentos y escritura
###### Incluyendo manejo de datos con pandas

In [77]:
import pandas as pd #Carga la libreria de Pandas y la asigna como "pd" pero igual puede tomar cualquier nombre a nuestra definición
import numpy as np # carga la libreria de Numpy y la asigna como "np" pero igual puede tomar cualquier nombre a nuestra definición

####Manejo de archivos con Pandas

In [78]:
with open  ("/content/sample_data/README.md","r") as File1:
  File_Content = File1.read()
  print(File_Content)
print(File1.close)

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://developers.google.com/machine-learning/crash-course/california-housing-data-description

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).

<built-in method close of _io.TextIOWrapper object at 0x7fda88173c90>

Para mayores referencias estas son las direcciónes con las que se pueden consultar el manejo de las librerías

Pandas:
https://pandas.pydata.org/docs/getting_started/index.html

Numpy:
https://numpy.org/devdocs/user/quickstart.html

##### Existen arreglos de 1 dimensión (Vectores)
##### Existen arreglos de 2 dimensiones ( Arrays )
##### Y por ultimo tenemos los arreglos de 3  Dimensiones (Cubicos)


In [79]:
a = np.arange(20).reshape(4, 5)

In [80]:
a.shape # Muestra su forma (Shape)

(4, 5)

In [81]:
a #Muestra simplemente el arreglo

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
type(a) #Muestra el tipo del arreglo

numpy.ndarray

In [83]:
b = np.arange(15).reshape(3, 5) #Nuevo arreglo de 15 valores

In [84]:
print("tipo de arreglo",type(b))
print("Arreglo:",a.shape)
print("Valor de'B'\n",b)


tipo de arreglo <class 'numpy.ndarray'>
Arreglo: (4, 5)
Valor de'B'
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [85]:
c=np.append(a,b) #Manejo de datos con numpy
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
       14])